# Generated by Django 2.0.1 on 2018-02-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('crn', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_id', models.TextField()),
                ('section', models.TextField()),
                ('title', models.TextField()),
                ('credit', models.FloatField()),
                ('room', models.TextField()),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('days', models.TextField()),
                ('students_max', models.IntegerField()),
                ('students_count', models.IntegerField()),
                ('instructor', models.TextField()),
                ('fees', models.FloatField()),
            ],
        ),
    ]
