# Generated by Django 2.0.1 on 2018-02-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='begin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='end',
            field=models.TimeField(),
        ),
    ]
